version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - network

  mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: P@sswd!@Root
      MYSQL_DATABASE: finance_challenge
      MYSQL_USER: finance_challenge
      MYSQL_PASSWORD: P@sswd!@User
    networks:
      - network

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    links:
      - app
    networks:
      - network

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=P@ssWd!@#10
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge
